---
sidebar: sidebar 
permalink: information/additional_resources.html 
keywords:  
summary:  
---
= Ressources supplémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous trouverez des ressources d'aide supplémentaires sur les services cloud et le support NetApp, ainsi que des informations générales sur REST et cloud.



== Astra

* https://["Documentation Astra Control Center 2108"^]
+
Documentation relative au logiciel Astra Control Center déployé sur le site du client.

* https://["Documentation relative au service après-vente Astra Control"^]
+
Documentation relative au logiciel Astra Control Service disponible dans le cloud public.

* https://["Documentation Astra Trident"^]
+
Documentation relative à l'orchestrateur de stockage open source Astra Trident géré par NetApp.





== Ressources cloud NetApp

* https://["Solutions cloud NetApp"^]
+
Site central des solutions clouds NetApp.

* https://["Console NetApp Cloud Central"^]
+
Console de services NetApp Cloud Central avec connexion.

* https://["Support NetApp"^]
+
Accédez aux outils de dépannage, à la documentation et à l'assistance technique.





== Concepts REST et technologie cloud

* Doctorat https://["thèse"^] Par Roy Fielding
+
Cette publication a introduit et établi le modèle de développement des applications REST.

* https://["Auth0"^]
+
Il s'agit du service de plateforme d'authentification et d'autorisation utilisé par le service Astra pour l'accès au Web.

* https://["Éditeur RFC"^]
+
Source faisant autorité pour les normes Web et Internet, maintenue comme un ensemble de documents RFC numérotés de façon unique.


